(()=>{'use strict';const $=id=>document.getElementById(id),C=window.ALBION_CONTENT||{},Q=window.ALBION_QUIZ||[],squad=C.squad||[];
const esc=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
function countdown(){const e=$('countdown');if(!e)return;const t=new Date('2026-08-23T14:00:00+01:00')-new Date();if(t<=0){e.textContent='Matchday';return}const d=Math.floor(t/864e5),h=Math.floor(t%864e5/36e5),m=Math.floor(t%36e5/6e4);e.innerHTML=`<b>${d}</b> days <b>${h}</b> hrs <b>${m}</b> mins`;}
const groups=['Goalkeeper','Defender','Midfielder','Forward'];function renderSquad(){const names={Goalkeeper:'Goalkeepers',Defender:'Defenders',Midfielder:'Midfielders',Forward:'Forwards'};$('squadBrowser').innerHTML=groups.map(g=>`<section class="position-group"><h3>${names[g]}</h3><ul>${squad.filter(p=>p.position===g).map(p=>`<li>${esc(p.name)}</li>`).join('')}</ul></section>`).join('');}
const formations={'4-2-3-1':['GK','RB','CB','CB','LB','DM','DM','RW','AM','LW','ST'],'4-3-3':['GK','RB','CB','CB','LB','CM','CM','CM','RW','ST','LW'],'3-4-2-1':['GK','CB','CB','CB','RWB','CM','CM','LWB','AM','AM','ST']};
const preferred={GK:'Bart Verbruggen',RB:'Jack Hinshelwood',CB:'Lewis Dunk',LB:'Maxim De Cuyper',DM:'Carlos Baleba',CM:'Mats Wieffer',RWB:'Ferdi Kadioglu',LWB:'Kaoru Mitoma',RW:'Yankuba Minteh',AM:'Georginio Rutter',LW:'Kaoru Mitoma',ST:'Danny Welbeck'};
function options(role){const map={GK:['Goalkeeper'],RB:['Defender','Midfielder'],LB:['Defender','Midfielder'],CB:['Defender'],DM:['Midfielder'],CM:['Midfielder'],RWB:['Defender','Midfielder'],LWB:['Defender','Midfielder'],RW:['Midfielder','Forward'],LW:['Midfielder','Forward'],AM:['Midfielder','Forward'],ST:['Forward']};return squad.filter(p=>map[role].includes(p.position));}
function renderPitch(vals=[]){const pitch=$('pitch');pitch.innerHTML='';formations[$('formation').value].forEach((role,i)=>{const cell=document.createElement('label');cell.className='player-slot';cell.innerHTML=`<span>${role}</span><select aria-label="${role} position"><option value="">Select player</option>${options(role).map(p=>`<option>${esc(p.name)}</option>`).join('')}</select>`;pitch.appendChild(cell);cell.querySelector('select').value=vals[i]||'';});pitch.querySelectorAll('select').forEach(s=>s.addEventListener('change',saveXI));}
function saveXI(){const vals=[...document.querySelectorAll('#pitch select')].map(s=>s.value),unique=new Set(vals.filter(Boolean));localStorage.setItem('albionXI',JSON.stringify({f:$('formation').value,v:vals}));$('xiMessage').textContent=vals.filter(Boolean).length===11?(unique.size===11?'Your complete XI is saved on this device.':'Choose eleven different players.'):`${vals.filter(Boolean).length}/11 positions selected.`;}
function predicted(){const used=new Set(),vals=formations[$('formation').value].map(role=>{let n=preferred[role];if(used.has(n)||!options(role).some(p=>p.name===n))n=options(role).find(p=>!used.has(p.name))?.name||'';used.add(n);return n});renderPitch(vals);saveXI();}
function initXI(){let saved={};try{saved=JSON.parse(localStorage.getItem('albionXI'))||{}}catch{}if(saved.f)$('formation').value=saved.f;renderPitch(saved.v);$('formation').addEventListener('change',()=>{renderPitch();saveXI()});$('loadPredicted').addEventListener('click',predicted);$('clearXI').addEventListener('click',()=>{localStorage.removeItem('albionXI');renderPitch();$('xiMessage').textContent='Line-up cleared.'});}
function renderFixtures(){const q=$('fixtureSearch').value.toLowerCase().trim(),v=$('venueFilter').value,list=(C.fixtures||[]).filter(f=>(v==='all'||f.venue===v)&&f.opponent.toLowerCase().includes(q));$('fixtureList').innerHTML=list.length?list.map(f=>`<article class="fixture-item"><div><b>${esc(f.date)}</b><small>Premier League</small></div><div><strong>${f.venue==='H'?'Albion v '+esc(f.opponent):esc(f.opponent)+' v Albion'}</strong><small>${f.venue==='H'?'Amex Stadium':'Away'}</small></div></article>`).join(''):'<p>No fixtures match that search.</p>';}
let current=[];function newQuiz(){const diff=$('quizDifficulty').value,pool=diff==='All'?Q:Q.filter(q=>q.difficulty===diff);current=[...pool].sort(()=>Math.random()-.5).slice(0,5);$('quizContainer').innerHTML=current.map((q,i)=>`<fieldset class="quiz-question"><legend>${i+1}. ${esc(q.question)}</legend>${q.options.map((o,j)=>`<label><input type="radio" name="q${i}" value="${j}"> ${esc(o)}</label>`).join('')}<div id="feedback${i}"></div></fieldset>`).join('');$('quizResult').textContent='';}
function checkQuiz(){let score=0,answered=0;current.forEach((q,i)=>{const a=document.querySelector(`input[name=q${i}]:checked`),box=$('feedback'+i);if(a){answered++;if(+a.value===q.answer)score++;box.innerHTML=`<div class="quiz-feedback"><b>${+a.value===q.answer?'Correct':'Answer: '+esc(q.options[q.answer])}</b><br>${esc(q.explanation)}</div>`}else box.innerHTML='<div class="quiz-feedback">No answer selected.</div>'});if(answered<5){$('quizResult').textContent='Answer all five questions before finishing.';return}const best=Math.max(score,Number(localStorage.getItem('albionQuizBest')||0));localStorage.setItem('albionQuizBest',best);$('bestScore').textContent=`Best: ${best}/5`;$('quizResult').textContent=`You scored ${score}/5.`;}
function predictor(){const names=squad.filter(p=>p.position!=='Goalkeeper').map(p=>p.name);$('firstScorer').innerHTML='<option>No scorer</option>'+names.map(n=>`<option>${esc(n)}</option>`).join('');$('motm').innerHTML=squad.map(p=>`<option>${esc(p.name)}</option>`).join('');$('savePrediction').addEventListener('click',()=>{const text=`Albion ${$('homeScore').value}-${$('awayScore').value} Aston Villa · First scorer: ${$('firstScorer').value} · Player of the match: ${$('motm').value}`;localStorage.setItem('albionPrediction',text);$('predictionSummary').textContent=text});$('predictionSummary').textContent=localStorage.getItem('albionPrediction')||'Make and save your prediction.';}
function randomContent(){const showFact=()=>{$('factText').textContent=C.facts[Math.floor(Math.random()*C.facts.length)]},showMemory=()=>{$('memoryText').textContent=C.memories[Math.floor(Math.random()*C.memories.length)]};showFact();showMemory();$('newFact').addEventListener('click',showFact);$('newMemory').addEventListener('click',showMemory);}
function weather(){const e=$('weatherPanel'),target='2026-08-23',days=(new Date(target+'T12:00:00')-new Date())/864e5;if(days>14){e.innerHTML='<b>Falmer weather</b><p>Forecasts are not reliable this far ahead. This panel will activate closer to matchday.</p>';return}fetch('https://api.open-meteo.com/v1/forecast?latitude=50.8616&longitude=-0.0837&daily=temperature_2m_max,temperature_2m_min,precipitation_probability_max&timezone=Europe%2FLondon').then(r=>r.json()).then(d=>{const i=d.daily.time.indexOf(target);e.innerHTML=i<0?'<b>Falmer weather</b><p>Matchday forecast is not yet available.</p>':`<b>Falmer weather</b><p>${Math.round(d.daily.temperature_2m_max[i])}°C high · ${Math.round(d.daily.temperature_2m_min[i])}°C low · ${Math.round(d.daily.precipitation_probability_max[i])}% rain chance</p>`}).catch(()=>e.innerHTML='<b>Falmer weather</b><p>Weather is temporarily unavailable.</p>');}
function amex(){const info={North:['North Stand','Home support behind the goal. A lively area on many matchdays.'],South:['South Stand','Includes the visiting-supporter area. Check your ticket for the correct entrance.'],East:['East Stand','Includes family seating and broad views across the pitch.'],West:['West Stand','The largest stand, with hospitality and central seating areas.']};document.querySelectorAll('[data-stand]').forEach(b=>b.addEventListener('click',()=>{$('standInfo').innerHTML=`<h3>${info[b.dataset.stand][0]}</h3><p>${info[b.dataset.stand][1]}</p>`}));}
function celebrate(){const modal=$('celebration');$('winConfetti').addEventListener('click',()=>{modal.classList.add('show');$('closeCelebration').focus();for(let i=0;i<44;i++){const x=document.createElement('i');x.className='confetti';x.style.left=Math.random()*100+'%';x.style.animationDelay=Math.random()*.8+'s';x.textContent=Math.random()>.45?'⌁':'◆';modal.appendChild(x)}});$('closeCelebration').addEventListener('click',()=>{modal.classList.remove('show');modal.querySelectorAll('.confetti').forEach(x=>x.remove())});}
function ui(){const menu=$('menuToggle'),nav=$('navLinks');menu.addEventListener('click',()=>{const open=nav.classList.toggle('open');menu.setAttribute('aria-expanded',open)});$('fixtureSearch').addEventListener('input',renderFixtures);$('venueFilter').addEventListener('change',renderFixtures);$('quizDifficulty').addEventListener('change',newQuiz);$('newQuiz').addEventListener('click',newQuiz);$('checkQuiz').addEventListener('click',checkQuiz);$('bestScore').textContent=`Best: ${localStorage.getItem('albionQuizBest')||0}/5`;}
countdown();setInterval(countdown,60000);renderSquad();initXI();renderFixtures();newQuiz();predictor();randomContent();weather();amex();celebrate();ui();})();