window.ALBION_CONTENT = {
  featureVersion: "24",
  lastUpdated: "28 July 2026",
  currentSeason: "2026/27",
  seasonDatabase: {
    "2026/27": {
      label: "2026/27",
      status: "Season not started",
      competition: "Premier League",
      played: 0,
      won: 0,
      drawn: 0,
      lost: 0,
      goalsFor: 0,
      goalsAgainst: 0,
      points: 0,
      position: null,
      results: [],
    },
  },
  freshness: {
    fixtures: "28 July 2026",
    squad: "28 July 2026",
    travel: "28 July 2026",
    history: "28 July 2026",
  },
  nextMatch: {
    opponent: "Aston Villa",
    opponentShort: "Villa",
    dateLong: "Sunday 23 August 2026",
    dateShort: "23 Aug",
    time: "14:00",
    venue: "Amex Stadium",
    dateISO: "2026-08-23T14:00:00+01:00",
    competition: "Premier League",
    status: "Confirmed opening fixture",
    broadcast: "Sky Sports",
    note: "Scheduled on Sunday following Albion's UEFA Conference League play-off on the preceding Thursday.",
  },
  squad: [
    { name: "Bart Verbruggen", position: "Goalkeeper" },
    { name: "Jason Steele", position: "Goalkeeper" },
    { name: "Tom McGill", position: "Goalkeeper" },
    { name: "Carl Rushworth", position: "Goalkeeper" },
    { name: "Pascal Struijk", position: "Defender" },
    { name: "Costinha", position: "Defender" },
    { name: "Michael Svoboda", position: "Defender" },
    { name: "Igor Julio", position: "Defender" },
    { name: "Lewis Dunk", position: "Defender" },
    { name: "Eiran Cashin", position: "Defender" },
    { name: "Olivier Boscagli", position: "Defender" },
    { name: "Ferdi Kadioglu", position: "Defender" },
    { name: "Maxim De Cuyper", position: "Defender" },
    { name: "Diego Coppola", position: "Defender" },
    { name: "Amario Cozier-Duberry", position: "Midfielder" },
    { name: "Rodrigo Rêgo", position: "Midfielder" },
    { name: "Brajan Gruda", position: "Midfielder" },
    { name: "Jack Hinshelwood", position: "Midfielder" },
    { name: "Carlos Baleba", position: "Midfielder" },
    { name: "Kaoru Mitoma", position: "Midfielder" },
    { name: "Diego Gómez", position: "Midfielder" },
    { name: "Yasin Ayari", position: "Midfielder" },
    { name: "Mats Wieffer", position: "Midfielder" },
    { name: "Pascal Groß", position: "Midfielder" },
    { name: "Matt O'Riley", position: "Midfielder" },
    { name: "Malick Yalcouyé", position: "Midfielder" },
    { name: "Facundo Buonanotte", position: "Midfielder" },
    { name: "Ibrahim Osman", position: "Forward" },
    { name: "Yoon Do-Young", position: "Forward" },
    { name: "Zadok Yohanna", position: "Forward" },
    { name: "Stefanos Tzimas", position: "Forward" },
    { name: "Georginio Rutter", position: "Forward" },
    { name: "Yankuba Minteh", position: "Forward" },
    { name: "Tom Watson", position: "Forward" },
    { name: "Danny Welbeck", position: "Forward" },
    { name: "Charalampos Kostoulas", position: "Forward" },
    { name: "Evan Ferguson", position: "Forward" },
    { name: "Mark O'Mahony", position: "Forward" },
  ],
  playerProfiles: [
    { name: "Bart Verbruggen", position: "Goalkeeper", role: "Goalkeeper", number: 1, nationality: "Netherlands", initials: "BV", summary: "Goalkeeper option in the current first-team squad." },
    { name: "Jason Steele", position: "Goalkeeper", role: "Goalkeeper", number: 23, nationality: "England", initials: "JS", summary: "Goalkeeper option in the current first-team squad." },
    { name: "Tom McGill", position: "Goalkeeper", role: "Goalkeeper", number: 38, nationality: "Canada", initials: "TM", summary: "Goalkeeper option in the current first-team squad." },
    { name: "Carl Rushworth", position: "Goalkeeper", role: "Goalkeeper", number: 39, nationality: "England", initials: "CR", summary: "Goalkeeper option in the current first-team squad." },
    { name: "Pascal Struijk", position: "Defender", role: "Centre-back", number: null, nationality: "Netherlands", initials: "PS", summary: "Centre-back option in the current first-team squad." },
    { name: "Costinha", position: "Defender", role: "Right-back", number: null, nationality: "Portugal", initials: "CO", summary: "Right-back option in the current first-team squad." },
    { name: "Michael Svoboda", position: "Defender", role: "Centre-back", number: null, nationality: "Austria", initials: "MS", summary: "Centre-back option in the current first-team squad." },
    { name: "Igor Julio", position: "Defender", role: "Centre-back", number: 3, nationality: "Brazil", initials: "IJ", summary: "Centre-back option in the current first-team squad." },
    { name: "Lewis Dunk", position: "Defender", role: "Centre-back", number: 5, nationality: "England", initials: "LD", summary: "Centre-back option in the current first-team squad." },
    { name: "Eiran Cashin", position: "Defender", role: "Centre-back", number: 16, nationality: "Ireland", initials: "EC", summary: "Centre-back option in the current first-team squad." },
    { name: "Olivier Boscagli", position: "Defender", role: "Centre-back / left-back", number: 21, nationality: "France", initials: "OB", summary: "Centre-back / left-back option in the current first-team squad." },
    { name: "Ferdi Kadioglu", position: "Defender", role: "Full-back / wing-back", number: 24, nationality: "Turkey", initials: "FK", summary: "Full-back / wing-back option in the current first-team squad." },
    { name: "Maxim De Cuyper", position: "Defender", role: "Left-back / wing-back", number: 29, nationality: "Belgium", initials: "MD", summary: "Left-back / wing-back option in the current first-team squad." },
    { name: "Diego Coppola", position: "Defender", role: "Centre-back", number: 42, nationality: "Italy", initials: "DC", summary: "Centre-back option in the current first-team squad." },
    { name: "Amario Cozier-Duberry", position: "Midfielder", role: "Wide midfielder", number: null, nationality: "England", initials: "AC", summary: "Wide midfielder option in the current first-team squad." },
    { name: "Rodrigo Rêgo", position: "Midfielder", role: "Attacking midfielder", number: null, nationality: "Portugal", initials: "RR", summary: "Attacking midfielder option in the current first-team squad." },
    { name: "Brajan Gruda", position: "Midfielder", role: "Attacking midfielder", number: 8, nationality: "Germany", initials: "BG", summary: "Attacking midfielder option in the current first-team squad." },
    { name: "Jack Hinshelwood", position: "Midfielder", role: "Central midfielder / full-back", number: 13, nationality: "England", initials: "JH", summary: "Central midfielder / full-back option in the current first-team squad." },
    { name: "Carlos Baleba", position: "Midfielder", role: "Central midfielder", number: 17, nationality: "Cameroon", initials: "CB", summary: "Central midfielder option in the current first-team squad." },
    { name: "Kaoru Mitoma", position: "Midfielder", role: "Left winger", number: 22, nationality: "Japan", initials: "KM", summary: "Left winger option in the current first-team squad." },
    { name: "Diego Gómez", position: "Midfielder", role: "Central midfielder", number: 25, nationality: "Paraguay", initials: "DG", summary: "Central midfielder option in the current first-team squad." },
    { name: "Yasin Ayari", position: "Midfielder", role: "Central midfielder", number: 26, nationality: "Sweden", initials: "YA", summary: "Central midfielder option in the current first-team squad." },
    { name: "Mats Wieffer", position: "Midfielder", role: "Defensive midfielder", number: 27, nationality: "Netherlands", initials: "MW", summary: "Defensive midfielder option in the current first-team squad." },
    { name: "Pascal Groß", position: "Midfielder", role: "Central midfielder", number: 30, nationality: "Germany", initials: "PG", summary: "Central midfielder option in the current first-team squad." },
    { name: "Matt O'Riley", position: "Midfielder", role: "Attacking midfielder", number: 33, nationality: "Denmark", initials: "MO", summary: "Attacking midfielder option in the current first-team squad." },
    { name: "Malick Yalcouyé", position: "Midfielder", role: "Central midfielder", number: 36, nationality: "Côte d’Ivoire", initials: "MY", summary: "Central midfielder option in the current first-team squad." },
    { name: "Facundo Buonanotte", position: "Midfielder", role: "Attacking midfielder", number: 40, nationality: "Argentina", initials: "FB", summary: "Attacking midfielder option in the current first-team squad." },
    { name: "Ibrahim Osman", position: "Forward", role: "Winger", number: null, nationality: "Ghana", initials: "IO", summary: "Winger option in the current first-team squad." },
    { name: "Yoon Do-Young", position: "Forward", role: "Winger", number: null, nationality: "South Korea", initials: "YD", summary: "Winger option in the current first-team squad." },
    { name: "Zadok Yohanna", position: "Forward", role: "Forward", number: null, nationality: "Nigeria", initials: "ZY", summary: "Forward option in the current first-team squad." },
    { name: "Stefanos Tzimas", position: "Forward", role: "Centre-forward", number: 9, nationality: "Greece", initials: "ST", summary: "Centre-forward option in the current first-team squad." },
    { name: "Georginio Rutter", position: "Forward", role: "Forward / attacking midfielder", number: 10, nationality: "France", initials: "GR", summary: "Forward / attacking midfielder option in the current first-team squad." },
    { name: "Yankuba Minteh", position: "Forward", role: "Right winger", number: 11, nationality: "Gambia", initials: "YM", summary: "Right winger option in the current first-team squad." },
    { name: "Tom Watson", position: "Forward", role: "Wide forward", number: 14, nationality: "England", initials: "TW", summary: "Wide forward option in the current first-team squad." },
    { name: "Danny Welbeck", position: "Forward", role: "Centre-forward", number: 18, nationality: "England", initials: "DW", summary: "Centre-forward option in the current first-team squad." },
    { name: "Charalampos Kostoulas", position: "Forward", role: "Forward", number: 19, nationality: "Greece", initials: "CK", summary: "Forward option in the current first-team squad." },
    { name: "Evan Ferguson", position: "Forward", role: "Centre-forward", number: 28, nationality: "Ireland", initials: "EF", summary: "Centre-forward option in the current first-team squad." },
    { name: "Mark O'Mahony", position: "Forward", role: "Centre-forward", number: 51, nationality: "Ireland", initials: "MM", summary: "Centre-forward option in the current first-team squad." },
  ],
  fixtures: [
    {
      date: "23 Aug 2026",
      opponent: "Aston Villa",
      venue: "H",
      time: "14:00",
      broadcast: "Sky Sports",
    },
    {
      date: "30 Aug 2026",
      opponent: "Chelsea",
      venue: "A",
      time: "14:00",
      broadcast: "Sky Sports",
    },
    {
      date: "5 Sep 2026",
      opponent: "Leeds United",
      venue: "H",
      time: "15:00",
    },
    {
      date: "13 Sep 2026",
      opponent: "Coventry City",
      venue: "A",
      time: "14:00",
      broadcast: "Sky Sports",
    },
    {
      date: "19 Sep 2026",
      opponent: "Arsenal",
      venue: "H",
      time: "15:00",
    },
    {
      date: "10 Oct 2026",
      opponent: "Sunderland",
      venue: "A",
    },
    {
      date: "17 Oct 2026",
      opponent: "Crystal Palace",
      venue: "H",
    },
    {
      date: "24 Oct 2026",
      opponent: "Liverpool",
      venue: "A",
    },
    {
      date: "31 Oct 2026",
      opponent: "Manchester City",
      venue: "A",
    },
    {
      date: "7 Nov 2026",
      opponent: "Brentford",
      venue: "H",
    },
    {
      date: "21 Nov 2026",
      opponent: "Hull City",
      venue: "A",
    },
    {
      date: "28 Nov 2026",
      opponent: "Newcastle United",
      venue: "H",
    },
    {
      date: "2 Dec 2026",
      opponent: "Bournemouth",
      venue: "A",
    },
    {
      date: "5 Dec 2026",
      opponent: "Nottingham Forest",
      venue: "A",
    },
    {
      date: "12 Dec 2026",
      opponent: "Everton",
      venue: "H",
    },
    {
      date: "19 Dec 2026",
      opponent: "Ipswich Town",
      venue: "H",
    },
    {
      date: "26 Dec 2026",
      opponent: "Fulham",
      venue: "A",
    },
    {
      date: "30 Dec 2026",
      opponent: "Tottenham Hotspur",
      venue: "A",
    },
    {
      date: "2 Jan 2027",
      opponent: "Manchester United",
      venue: "H",
    },
    {
      date: "6 Jan 2027",
      opponent: "Bournemouth",
      venue: "H",
    },
    {
      date: "16 Jan 2027",
      opponent: "Brentford",
      venue: "A",
    },
    {
      date: "23 Jan 2027",
      opponent: "Manchester City",
      venue: "H",
    },
    {
      date: "30 Jan 2027",
      opponent: "Newcastle United",
      venue: "A",
    },
    {
      date: "6 Feb 2027",
      opponent: "Hull City",
      venue: "H",
    },
    {
      date: "10 Feb 2027",
      opponent: "Manchester United",
      venue: "A",
    },
    {
      date: "20 Feb 2027",
      opponent: "Tottenham Hotspur",
      venue: "H",
    },
    {
      date: "27 Feb 2027",
      opponent: "Ipswich Town",
      venue: "A",
    },
    {
      date: "3 Mar 2027",
      opponent: "Fulham",
      venue: "H",
    },
    {
      date: "13 Mar 2027",
      opponent: "Leeds United",
      venue: "A",
    },
    {
      date: "20 Mar 2027",
      opponent: "Coventry City",
      venue: "H",
    },
    {
      date: "10 Apr 2027",
      opponent: "Aston Villa",
      venue: "A",
    },
    {
      date: "17 Apr 2027",
      opponent: "Chelsea",
      venue: "H",
    },
    {
      date: "24 Apr 2027",
      opponent: "Everton",
      venue: "A",
    },
    {
      date: "1 May 2027",
      opponent: "Nottingham Forest",
      venue: "H",
    },
    {
      date: "8 May 2027",
      opponent: "Sunderland",
      venue: "H",
    },
    {
      date: "15 May 2027",
      opponent: "Crystal Palace",
      venue: "A",
    },
    {
      date: "23 May 2027",
      opponent: "Liverpool",
      venue: "H",
    },
    {
      date: "30 May 2027",
      opponent: "Arsenal",
      venue: "A",
    },
  ],
  facts: [
    "Brighton & Hove Albion were founded in 1901.",
    "Albion are known as the Seagulls.",
    "The Goldstone Ground was Albion’s home from 1902 to 1997.",
    "The 1–1 draw at Hereford in 1997 preserved Albion’s Football League status.",
    "Albion played home matches at Gillingham before returning to Brighton at Withdean.",
    "The Amex opened in 2011.",
    "Albion reached the FA Cup final in 1983.",
    "Brighton won promotion to the Premier League in 2017.",
    "The club first qualified for European football in 2023.",
    "Albion played their first European campaign in the 2023/24 Europa League.",
    "Blue and white stripes are Albion’s traditional home colours.",
    "Lewis Dunk came through Albion’s youth system.",
    "Peter Ward remains one of the club’s most celebrated goalscorers.",
    "The rivalry with Crystal Palace is one of English football’s most distinctive.",
    "Albion won the League One title in 2010/11.",
    "The Amex stands in Falmer, between Brighton and Lewes.",
    "The club’s women’s team also plays under the Brighton & Hove Albion name.",
    "The phrase “Together making history” is strongly associated with the club.",
    "The North Stand is the main singing end at the Amex.",
    "Albion’s first Premier League season was 2017/18.",
  ],
  memories: [
    "The final whistle at Hereford in 1997, when Albion preserved their Football League status.",
    "The first competitive match at the Amex in 2011.",
    "Promotion to the Premier League under Chris Hughton in 2017.",
    "Pascal Groß scoring Albion's first Premier League goal.",
    "The club's first European night at the Amex in 2023.",
    "Glenn Murray's goals across two memorable spells with Albion.",
    "Bobby Zamora leading the attack during Albion's climb through the divisions.",
    "The supporters' long campaign for a permanent home at Falmer.",
    "The last match at the Goldstone Ground in 1997.",
    "Albion reaching the FA Cup final at Wembley in 1983.",
    "The Withdean years, when temporary surroundings helped keep the club moving forward.",
    "Lewis Dunk progressing from the academy to captain Albion in the Premier League.",
  ],
};
