(()=>{'use strict';
const $=id=>document.getElementById(id), canvas=$('psCanvas'); if(!canvas)return; const c=canvas.getContext('2d');
const W=960,H=600, goal={x:220,y:115,w:520,h:205,lineY:320};
const brighton=['Danny Welbeck','Georginio Rutter','Yankuba Minteh','Diego Gómez','Maxim De Cuyper'];
const palace=['Palace taker 1','Palace taker 2','Palace taker 3','Palace taker 4','Palace taker 5'];
let state, selected=null, anim=null, raf=0, saveOpen=false;
const targets={tl:[285,155],tc:[480,150],tr:[675,155],ml:[285,225],mc:[480,225],mr:[675,225],bl:[285,292],bc:[480,292],br:[675,292]};
function reset(){state={phase:'shoot',round:0,a:[],p:[],scoreA:0,scoreP:0,done:false};selected=null;anim=null;saveOpen=false; $('psNext').hidden=true;$('psShootControls').hidden=false;$('psSaveControls').hidden=true;setMsg('Pick a target');renderUI();draw();}
function renderUI(){ $('psScore').textContent=`${state.scoreA}–${state.scoreP}`; $('psAlbionMarks').innerHTML=marks(state.a); $('psPalaceMarks').innerHTML=marks(state.p); $('psPhase').textContent=state.phase==='shoot'?'ALBION PENALTY':'PALACE PENALTY · YOU ARE IN GOAL'; $('psPlayer').textContent=state.phase==='shoot'?brighton[Math.min(state.round,4)]:palace[Math.min(state.round,4)];}
function marks(a){return [...Array(5)].map((_,i)=>`<i class="ps-mark ${a[i]===true?'goal':a[i]===false?'miss':''}"></i>`).join('')}
function setMsg(x){$('psMessage').textContent=x}
function ease(t){return 1-Math.pow(1-t,3)}
function line(x1,y1,x2,y2,w,col){c.strokeStyle=col;c.lineWidth=w;c.beginPath();c.moveTo(x1,y1);c.lineTo(x2,y2);c.stroke()}
function drawPitch(){let g=c.createLinearGradient(0,0,0,H);g.addColorStop(0,'#164c34');g.addColorStop(1,'#278a55');c.fillStyle=g;c.fillRect(0,0,W,H);for(let i=0;i<10;i++){c.fillStyle=i%2?'rgba(255,255,255,.018)':'rgba(0,0,0,.025)';c.fillRect(i*96,0,96,H)}c.strokeStyle='rgba(255,255,255,.85)';c.lineWidth=3;c.strokeRect(130,300,700,245);c.strokeRect(270,300,420,105);c.beginPath();c.arc(480,410,95,Math.PI*1.15,Math.PI*1.85);c.stroke();c.fillStyle='#fff';c.beginPath();c.arc(480,455,5,0,7);c.fill()}
function drawGoal(){c.save();c.strokeStyle='#fff';c.lineWidth=10;c.lineJoin='round';c.strokeRect(goal.x,goal.y,goal.w,goal.h);c.strokeStyle='rgba(225,240,255,.38)';c.lineWidth=1;for(let x=goal.x;x<=goal.x+goal.w;x+=26)line(x,goal.y,x,goal.lineY,1,'rgba(225,240,255,.32)');for(let y=goal.y;y<=goal.lineY;y+=20)line(goal.x,y,goal.x+goal.w,y,1,'rgba(225,240,255,.32)');c.restore()}
function drawCrowd(){c.fillStyle='#102239';c.fillRect(0,0,W,118);for(let i=0;i<260;i++){c.fillStyle=['#fff','#1675c1','#d31d45','#1d2c47'][i%4];c.fillRect((i*37)%W,20+((i*19)%80),4,4)}}
function drawKeeper(x=480,y=320,rot=0,scale=1){c.save();c.translate(x,y);c.rotate(rot);c.scale(scale,scale);c.lineCap='round';c.strokeStyle='#e9b72e';c.lineWidth=22;line(-34,-76,-62,-35,20,'#e9b72e');line(34,-76,62,-35,20,'#e9b72e');c.fillStyle='#f5c835';roundRect(-42,-105,84,76,18);c.fill();c.fillStyle='#18243b';roundRect(-40,-32,80,33,7);c.fill();line(-22,-2,-27,43,20,'#18243b');line(22,-2,27,43,20,'#18243b');line(-27,43,-42,47,12,'#111');line(27,43,42,47,12,'#111');c.fillStyle='#b87957';c.beginPath();c.arc(0,-128,21,0,7);c.fill();c.fillStyle='#f6f6f6';c.beginPath();c.arc(-66,-31,10,0,7);c.arc(66,-31,10,0,7);c.fill();c.restore()}
function roundRect(x,y,w,h,r){c.beginPath();c.roundRect(x,y,w,h,r)}
function drawTaker(x=480,y=522,lean=0){c.save();c.translate(x,y);c.rotate(lean);c.fillStyle='#1268b2';roundRect(-35,-118,70,78,18);c.fill();c.fillStyle='#fff';c.fillRect(-12,-116,24,74);c.fillStyle='#0b57a0';roundRect(-35,-42,70,31,6);c.fill();line(-20,-10,-25,38,18,'#f4f4f4');line(20,-10,25,38,18,'#f4f4f4');line(-25,38,-41,44,11,'#101010');line(25,38,41,44,11,'#101010');line(-33,-95,-52,-52,17,'#b97b59');line(33,-95,52,-52,17,'#b97b59');c.fillStyle='#b97b59';c.beginPath();c.arc(0,-144,19,0,7);c.fill();c.fillStyle='#18120f';c.beginPath();c.arc(0,-151,19,Math.PI,Math.PI*2);c.fill();c.fillStyle='#fff';c.font='bold 12px Arial';c.textAlign='center';c.fillText('ALBION',0,-86);c.font='bold 24px Arial';c.fillText('9',0,-58);c.restore()}
function drawBall(x=480,y=455,r=9){c.fillStyle='#fff';c.beginPath();c.arc(x,y,r,0,7);c.fill();c.strokeStyle='#222';c.lineWidth=1;c.stroke()}
function draw(){cancelAnimationFrame(raf);c.clearRect(0,0,W,H);drawCrowd();drawPitch();drawGoal();let kx=480,ky=320,kr=0,ks=1,tx=480,ty=522,lean=0,bx=480,by=455;if(anim){let now=performance.now(),t=Math.min(1,(now-anim.start)/anim.duration),e=ease(t);if(anim.type==='shoot'){tx=480+(anim.runX-480)*Math.min(1,e*1.3);ty=522-35*Math.min(1,e*1.4);lean=-.1*e;if(t>.38){let u=(t-.38)/.62;bx=480+(anim.target[0]-480)*u;by=455+(anim.target[1]-455)*u-90*Math.sin(Math.PI*u)*(anim.high?1:.35)}if(t>anim.reactAt){let u=(t-anim.reactAt)/(1-anim.reactAt);kx=480+(anim.kDest[0]-480)*ease(Math.min(1,u));ky=320+(anim.kDest[1]-320)*ease(Math.min(1,u));kr=anim.kRot*ease(Math.min(1,u));}if(t>=1)finishAnim();}
if(anim&&anim.type==='palace'){tx=480;ty=500;if(t>.35){let u=(t-.35)/.65;bx=480+(anim.target[0]-480)*u;by=455+(anim.target[1]-455)*u-55*Math.sin(Math.PI*u)}if(anim.userDive&&t>anim.userDive.at){let u=(t-anim.userDive.at)/(1-anim.userDive.at);kx=480+(anim.userDive.x-480)*ease(Math.min(1,u));ky=320+(anim.userDive.y-320)*ease(Math.min(1,u));kr=anim.userDive.rot*ease(Math.min(1,u))}if(t>=1)finishAnim();}}
drawKeeper(kx,ky,kr,ks);if(state.phase==='shoot'||anim?.type==='shoot')drawTaker(tx,ty,lean);else drawTaker(480,500,.03);drawBall(bx,by);if(anim)raf=requestAnimationFrame(draw)}
function kick(){if(!selected||anim||state.done)return;let target=targets[selected],power=+$('psPower').value;let lane=selected.endsWith('l')?'left':selected.endsWith('r')?'right':'centre';let keeperLane=Math.random()<.42?lane:['left','centre','right'][Math.floor(Math.random()*3)];let saved=keeperLane===lane&&Math.random()<(power<55?.62:.46);let miss=power>94&&Math.random()<.36;let kDest=keeperLane==='left'?[285,270]:keeperLane==='right'?[675,270]:[480,285];anim={type:'shoot',start:performance.now(),duration:1150,runX:455,target,high:selected[0]==='t',reactAt:.47+Math.random()*.08,kDest,kRot:keeperLane==='left'?-1.05:keeperLane==='right'?1.05:0,result:miss?'miss':saved?'save':'goal'};setMsg('Welbeck runs up…');$('psKick').disabled=true;draw()}
function beginPalace(){state.phase='save';selected=null;renderUI();$('psShootControls').hidden=true;$('psSaveControls').hidden=false;setMsg('Wait for the strike…');saveOpen=false;let keys=Object.keys(targets),key=keys[Math.floor(Math.random()*keys.length)];anim={type:'palace',start:performance.now(),duration:1500,target:targets[key],key,result:null,userDive:null};setTimeout(()=>{saveOpen=true;setMsg('DIVE NOW!')},620);draw()}
function save(dir){if(!anim||anim.type!=='palace'||!saveOpen||anim.userDive)return;let x=dir==='left'?285:dir==='right'?675:480,y=dir==='centre'?285:270,rot=dir==='left'?-1.05:dir==='right'?1.05:0;anim.userDive={at:(performance.now()-anim.start)/anim.duration,x,y,rot};let lane=anim.key.endsWith('l')?'left':anim.key.endsWith('r')?'right':'centre';let delay=anim.userDive.at;anim.result=(dir===lane&&delay<.78&&Math.random()<.72)?'save':'goal';setMsg('Verbruggen reacts!')}
function finishAnim(){let a=anim;anim=null;cancelAnimationFrame(raf);if(a.type==='shoot'){let goal=a.result==='goal';state.a.push(goal);if(goal)state.scoreA++;setMsg(goal?'GOAL!':a.result==='save'?'SAVED!':'MISSED!');$('psNext').hidden=false;}else{if(!a.result)a.result='goal';let goal=a.result==='goal';state.p.push(goal);if(goal)state.scoreP++;setMsg(goal?'Palace score':'VERBRUGGEN SAVES!');state.round++;$('psNext').hidden=false;}renderUI();draw();checkDone()}
function checkDone(){let kicksA=state.a.length,kicksP=state.p.length,remA=5-kicksA,remP=5-kicksP;if(state.scoreA>state.scoreP+remP||state.scoreP>state.scoreA+remA||(kicksA>=5&&kicksP>=5&&state.scoreA!==state.scoreP)){state.done=true;$('psNext').hidden=true;setMsg(state.scoreA>state.scoreP?'BRIGHTON WIN THE SHOOT-OUT!':'PALACE WIN THE SHOOT-OUT');}}
function next(){if(state.done)return;if(state.phase==='shoot')beginPalace();else{state.phase='shoot';$('psShootControls').hidden=false;$('psSaveControls').hidden=true;$('psNext').hidden=true;renderUI();setMsg('Pick a target');draw()}}
document.querySelectorAll('[data-shot]').forEach(b=>b.onclick=()=>{selected=b.dataset.shot;document.querySelectorAll('[data-shot]').forEach(x=>x.classList.toggle('selected',x===b));$('psKick').disabled=false;setMsg('Set power, then shoot')});document.querySelectorAll('[data-save]').forEach(b=>b.onclick=()=>save(b.dataset.save));$('psPower').oninput=e=>$('psPowerOut').textContent=e.target.value+'%';$('psKick').onclick=kick;$('psNext').onclick=next;$('psRestart').onclick=reset;reset();
})();
