(()=>{'use strict';
const $=id=>document.getElementById(id), canvas=$('psCanvas'); if(!canvas)return; const c=canvas.getContext('2d');
const W=960,H=600, goal={x:220,y:112,w:520,h:208,lineY:320};
const albion=[['WELBECK',18,'R'],['RUTTER',14,'L'],['MINTEH',17,'R'],['GÓMEZ',8,'R'],['DE CUYPER',29,'L']];
const palace=[['MATETA',14,'R'],['SARR',7,'R'],['KAMADA',18,'R'],['EZE',10,'R'],['LACROIX',5,'R']];
const targets={tl:[280,153],tc:[480,148],tr:[680,153],ml:[280,224],mc:[480,224],mr:[680,224],bl:[280,293],bc:[480,293],br:[680,293]};
let state,selected=null,anim=null,raf=0,meterRaf=0,meterStart=0,meterPos=.5,meterDir=1,meterRunning=false,saveOpen=false,sound=false,gestureStart=performance.now();
const clamp=(v,a,b)=>Math.max(a,Math.min(b,v)), ease=t=>1-Math.pow(1-t,3), lerp=(a,b,t)=>a+(b-a)*t;
function setMsg(x){$('psMessage').textContent=x}
function reset(){cancelAnimationFrame(raf);cancelAnimationFrame(meterRaf);state={phase:'shoot',round:0,a:[],p:[],scoreA:0,scoreP:0,done:false};selected=null;anim=null;saveOpen=false;meterRunning=false;meterPos=.5;gestureStart=performance.now();$('psNext').hidden=true;$('psShootControls').hidden=false;$('psSaveControls').hidden=true;$('psKick').disabled=true;$('psKick').textContent='Start run-up';document.querySelectorAll('[data-shot]').forEach(b=>b.classList.remove('selected'));setMsg('Choose a target');renderUI();draw();}
function marks(a){return [...Array(5)].map((_,i)=>`<i class="ps-mark ${a[i]===true?'goal':a[i]===false?'miss':''}"></i>`).join('')}
function renderUI(){ $('psScore').textContent=`${state.scoreA}–${state.scoreP}`;$('psAlbionMarks').innerHTML=marks(state.a);$('psPalaceMarks').innerHTML=marks(state.p);$('psPhase').textContent=state.phase==='shoot'?'ALBION PENALTY':'PALACE PENALTY · YOU ARE IN GOAL';$('psPlayer').textContent=(state.phase==='shoot'?albion:palace)[Math.min(state.round,4)][0];}
function line(x1,y1,x2,y2,w,col){c.strokeStyle=col;c.lineWidth=w;c.beginPath();c.moveTo(x1,y1);c.lineTo(x2,y2);c.stroke()}
function rr(x,y,w,h,r){c.beginPath();c.roundRect(x,y,w,h,r)}
function drawCrowd(){let g=c.createLinearGradient(0,0,0,125);g.addColorStop(0,'#071426');g.addColorStop(1,'#163b61');c.fillStyle=g;c.fillRect(0,0,W,125);for(let i=0;i<300;i++){c.fillStyle=['#f7f7f7','#1979c8','#d72745','#23344e'][i%4];c.beginPath();c.arc((i*41)%W,18+((i*23)%88),2.2,0,7);c.fill()}}
function drawPitch(){let g=c.createLinearGradient(0,120,0,H);g.addColorStop(0,'#185e3d');g.addColorStop(1,'#2b965b');c.fillStyle=g;c.fillRect(0,120,W,H-120);for(let i=0;i<12;i++){c.fillStyle=i%2?'rgba(255,255,255,.022)':'rgba(0,0,0,.025)';c.fillRect(i*80,120,80,H-120)}c.strokeStyle='rgba(255,255,255,.88)';c.lineWidth=3;c.strokeRect(128,300,704,250);c.strokeRect(272,300,416,106);c.beginPath();c.arc(480,455,94,Math.PI*1.15,Math.PI*1.85);c.stroke();c.fillStyle='#fff';c.beginPath();c.arc(480,455,5,0,7);c.fill()}
function drawGoal(){c.save();c.strokeStyle='rgba(220,238,250,.4)';c.lineWidth=1;for(let x=goal.x;x<=goal.x+goal.w;x+=26)line(x,goal.y,x,goal.lineY,1,'rgba(225,240,255,.36)');for(let y=goal.y;y<=goal.lineY;y+=20)line(goal.x,y,goal.x+goal.w,y,1,'rgba(225,240,255,.36)');c.strokeStyle='#fff';c.lineWidth=10;c.lineJoin='round';c.strokeRect(goal.x,goal.y,goal.w,goal.h);c.restore()}
function drawKeeper(x=480,y=320,rot=0,pose='ready',s=1){c.save();c.translate(x,y);c.rotate(rot);c.scale(s,s);c.lineCap='round';let armL=[-35,-80,-68,-48],armR=[35,-80,68,-48];if(pose==='point'){armR=[34,-82,82,-104]}if(pose==='bar'){armL=[-30,-82,-18,-190];armR=[30,-82,18,-190]}if(pose==='dive'){armL=[-28,-85,-86,-93];armR=[28,-85,86,-93]}
line(...armL,19,'#25a96b');line(...armR,19,'#25a96b');c.fillStyle='#28b777';rr(-43,-111,86,78,18);c.fill();c.fillStyle='#12314f';rr(-40,-35,80,34,7);c.fill();line(-23,-1,-31,45,19,'#12314f');line(23,-1,31,45,19,'#12314f');line(-31,45,-46,48,11,'#111');line(31,45,46,48,11,'#111');c.fillStyle='#b87957';c.beginPath();c.arc(0,-134,21,0,7);c.fill();c.fillStyle='#15120f';c.beginPath();c.arc(0,-141,21,Math.PI,Math.PI*2);c.fill();c.fillStyle='#fff';c.beginPath();c.arc(armL[2],armL[3],10,0,7);c.arc(armR[2],armR[3],10,0,7);c.fill();c.fillStyle='#fff';c.font='bold 12px Arial';c.textAlign='center';c.fillText('BHAFC',0,-72);c.restore()}
function drawTaker(x=480,y=526,lean=0,step=0,player=albion[0],placing=false){c.save();c.translate(x,y);c.rotate(lean);let blue='#1268b2',white='#f5f7fb',skin='#b97b59';if(placing)c.rotate(.08);c.lineCap='round';line(-31,-94,-48,-52+(placing?30:0),16,skin);line(31,-94,48,-52+(placing?30:0),16,skin);c.fillStyle=blue;rr(-37,-121,74,82,18);c.fill();c.fillStyle=white;c.fillRect(-10,-119,20,77);c.fillStyle=blue;rr(-38,-42,76,32,7);c.fill();let lSwing=Math.sin(step*Math.PI*2)*10;line(-21,-10,-28+lSwing,38,18,white);line(21,-10,28-lSwing,38,18,white);line(-28+lSwing,38,-43+lSwing,44,11,'#111');line(28-lSwing,38,43-lSwing,44,11,'#111');c.fillStyle=skin;c.beginPath();c.arc(0,-145,19,0,7);c.fill();c.fillStyle='#18120f';c.beginPath();c.arc(0,-152,19,Math.PI,Math.PI*2);c.fill();c.fillStyle='#fff';c.textAlign='center';c.font='bold 10px Arial';c.fillText(player[0],0,-88);c.font='bold 24px Arial';c.fillText(player[1],0,-58);c.restore()}
function drawBall(x=480,y=455,r=9){c.save();c.shadowColor='rgba(0,0,0,.28)';c.shadowBlur=5;c.shadowOffsetY=3;c.fillStyle='#fff';c.beginPath();c.arc(x,y,r,0,7);c.fill();c.shadowColor='transparent';c.strokeStyle='#222';c.lineWidth=1;c.stroke();c.restore()}
function keeperIdle(now){let t=(now-gestureStart)/1000;if(t<.8)return {y:320,pose:'bar'};if(t<1.5)return {y:320,pose:'ready'};if(t<2.2)return {y:320,pose:'point'};return {y:320+Math.sin(t*5)*2,pose:'ready'}}
function draw(){cancelAnimationFrame(raf);let now=performance.now();c.clearRect(0,0,W,H);drawCrowd();drawPitch();drawGoal();let k={x:480,y:320,rot:0,pose:'ready',s:1},t={x:480,y:526,lean:0,step:0,placing:false},b={x:480,y:455,r:9};if(!anim){let idle=keeperIdle(now);k.y=idle.y;k.pose=idle.pose}
if(anim){let u=clamp((now-anim.start)/anim.duration,0,1),e=ease(u);if(anim.type==='setup'){if(u<.32){t.x=lerp(560,500,e);t.y=lerp(515,482,e);t.placing=true;b.x=lerp(550,480,e);b.y=lerp(492,455,e)}else if(u<.52){t.x=500;t.y=482;t.placing=true}else{let q=(u-.52)/.48;t.x=lerp(500,480,q);t.y=lerp(482,526,q)}if(u>=1)startMeter()}
if(anim.type==='shoot'){let strike=.42;if(u<strike){let q=u/strike;t.x=lerp(480,462,ease(q));t.y=lerp(526,485,ease(q));t.lean=-.12*q;t.step=q*2}else{let q=(u-strike)/(1-strike);t.x=462;t.y=485;t.lean=-.18*(1-q);t.step=2;b.x=lerp(480,anim.target[0],q);b.y=lerp(455,anim.target[1],q)-anim.arc*Math.sin(Math.PI*q);if(q>anim.react){let r=(q-anim.react)/(1-anim.react);k.x=lerp(480,anim.kx,ease(r));k.y=lerp(320,anim.ky,ease(r));k.rot=anim.krot*ease(r);k.pose='dive';k.s=1+.05*Math.sin(Math.PI*r)}}if(u>=1)finishAnim()}
if(anim.type==='palace'){if(u<.30){t.x=lerp(560,500,e);t.y=lerp(515,482,e);t.placing=true;b.x=lerp(550,480,e);b.y=lerp(492,455,e)}else if(u<.47){t.x=500;t.y=482;t.placing=true}else if(u<.68){let q=(u-.47)/.21;t.x=lerp(500,520,q);t.y=lerp(482,526,q)}else{let q=(u-.68)/.32;t.x=lerp(520,462,ease(q));t.y=lerp(526,485,ease(q));t.lean=-.14*q;t.step=q*2;if(q>.55){let z=(q-.55)/.45;b.x=lerp(480,anim.target[0],z);b.y=lerp(455,anim.target[1],z)-anim.arc*Math.sin(Math.PI*z)}}if(anim.userDive){let r=clamp((now-anim.userDive.at)/520,0,1);k.x=lerp(480,anim.userDive.x,ease(r));k.y=lerp(320,anim.userDive.y,ease(r));k.rot=anim.userDive.rot*ease(r);k.pose='dive'}if(u>=1)finishAnim()}}
drawKeeper(k.x,k.y,k.rot,k.pose,k.s);drawTaker(t.x,t.y,t.lean,t.step,state.phase==='shoot'?albion[Math.min(state.round,4)]:palace[Math.min(state.round,4)],t.placing);drawBall(b.x,b.y,b.r);if(anim||!state.done)raf=requestAnimationFrame(draw)}
function startSetup(){if(!selected||anim||state.done)return;$('psKick').disabled=true;setMsg('The ball is placed carefully…');anim={type:'setup',start:performance.now(),duration:1500};draw()}
function startMeter(){anim=null;meterRunning=true;meterStart=performance.now();$('psKick').disabled=false;$('psKick').textContent='STOP BAR & SHOOT';setMsg('Stop the pointer in green');tickMeter()}
function tickMeter(){if(!meterRunning)return;let t=(performance.now()-meterStart)/1000;meterPos=(Math.sin(t*4.6-Math.PI/2)+1)/2;$('psPointer').style.left=(meterPos*100)+'%';let zone=meterPos<.14||meterPos>.86?'Red':meterPos<.34||meterPos>.66?'Amber':'Green';$('psPowerOut').textContent=zone;meterRaf=requestAnimationFrame(tickMeter)}
function shoot(){if(!selected||state.done)return;if(!meterRunning){startSetup();return}meterRunning=false;cancelAnimationFrame(meterRaf);$('psKick').disabled=true;$('psKick').textContent='Start run-up';let target=[...targets[selected]],quality=1-Math.abs(meterPos-.5)*2,lane=selected.endsWith('l')?'left':selected.endsWith('r')?'right':'centre';let miss=quality<.22&&Math.random()<.72;if(miss){target[0]+=meterPos<.5?-95:95;target[1]-=quality<.12?90:0}let keeperLane=Math.random()<(.30+.22*(1-quality))?lane:['left','centre','right'][Math.floor(Math.random()*3)];let save=keeperLane===lane&&!miss&&Math.random()<(quality>.75?.34:.58);let dest=keeperLane==='left'?[292,252]:keeperLane==='right'?[668,252]:[480,270];let high=selected[0]==='t';anim={type:'shoot',start:performance.now(),duration:1220,target,arc:high?95:28,react:.14+Math.random()*.09,kx:dest[0],ky:dest[1],krot:keeperLane==='left'?-1.12:keeperLane==='right'?1.12:0,result:miss?'miss':save?'save':'goal'};setMsg(`${albion[Math.min(state.round,4)][0]} runs up…`);draw()}
function beginPalace(){state.phase='save';selected=null;renderUI();$('psShootControls').hidden=true;$('psSaveControls').hidden=false;$('psNext').hidden=true;setMsg('Watch the taker…');saveOpen=false;let keys=Object.keys(targets),key=keys[Math.floor(Math.random()*keys.length)];anim={type:'palace',start:performance.now(),duration:2100,target:targets[key],key,arc:key[0]==='t'?85:30,result:null,userDive:null};setTimeout(()=>{if(anim?.type==='palace'){saveOpen=true;setMsg('DIVE NOW!')}},1430);draw()}
function save(dir){if(!anim||anim.type!=='palace'||!saveOpen||anim.userDive)return;let x=dir==='left'?292:dir==='right'?668:480,y=dir==='centre'?270:252,rot=dir==='left'?-1.12:dir==='right'?1.12:0;anim.userDive={at:performance.now(),x,y,rot};let lane=anim.key.endsWith('l')?'left':anim.key.endsWith('r')?'right':'centre';let reaction=(performance.now()-anim.start)/anim.duration;anim.result=(dir===lane&&reaction<.88&&Math.random()<.78)?'save':'goal';setMsg('Verbruggen reacts!')}
function finishAnim(){let a=anim;anim=null;cancelAnimationFrame(raf);if(a.type==='setup')return;if(a.type==='shoot'){let goal=a.result==='goal';state.a.push(goal);if(goal)state.scoreA++;setMsg(goal?'GOAL!':a.result==='save'?'SAVED!':'MISSED!');$('psNext').hidden=false}else{if(!a.result)a.result='goal';let goal=a.result==='goal';state.p.push(goal);if(goal)state.scoreP++;setMsg(goal?'Palace score':'VERBRUGGEN SAVES!');state.round++;$('psNext').hidden=false}renderUI();draw();checkDone()}
function checkDone(){let ka=state.a.length,kp=state.p.length,ra=Math.max(0,5-ka),rp=Math.max(0,5-kp);if(state.scoreA>state.scoreP+rp||state.scoreP>state.scoreA+ra||(ka>=5&&kp>=5&&state.scoreA!==state.scoreP)){state.done=true;$('psNext').hidden=true;setMsg(state.scoreA>state.scoreP?'BRIGHTON WIN THE SHOOT-OUT!':'PALACE WIN THE SHOOT-OUT');}}
function next(){if(state.done)return;if(state.phase==='shoot')beginPalace();else{state.phase='shoot';$('psShootControls').hidden=false;$('psSaveControls').hidden=true;$('psNext').hidden=true;renderUI();setMsg('Choose a target');$('psKick').disabled=true;document.querySelectorAll('[data-shot]').forEach(b=>b.classList.remove('selected'));gestureStart=performance.now();draw()}}
document.querySelectorAll('[data-shot]').forEach(b=>b.addEventListener('click',()=>{if(anim||meterRunning)return;selected=b.dataset.shot;document.querySelectorAll('[data-shot]').forEach(x=>x.classList.toggle('selected',x===b));$('psKick').disabled=false;setMsg('Press start run-up')}));document.querySelectorAll('[data-save]').forEach(b=>b.addEventListener('click',()=>save(b.dataset.save)));$('psKick').addEventListener('click',shoot);$('psNext').addEventListener('click',next);$('psRestart').addEventListener('click',reset);$('psSound').addEventListener('click',()=>{sound=!sound;$('psSound').textContent=sound?'Sound on':'Sound off';$('psSound').setAttribute('aria-pressed',String(sound))});reset();
})();
