(()=>{'use strict';
const $=id=>document.getElementById(id),wait=ms=>new Promise(r=>setTimeout(r,ms));
function replace(id){const n=$(id);if(!n)return null;const c=n.cloneNode(true);n.replaceWith(c);return c}
function initShootout(){
 const goal=replace('goal'),reset=replace('resetShootout'),panenka=replace('panenkaButton'),cont=replace('continueShootout');if(!goal)return;
 const card=$('shootout'),keeper=$('keeper'),taker=$('penaltyTaker'),ball=$('ball'),shadow=$('ballShadow'),pointer=$('aimPointer'),status=$('shootoutStatus'),badge=$('turnBadge'),ready=$('turnReadyPanel'),readyText=$('turnReadyText');
 const names=[['João Pedro','9'],['Danny Welbeck','18'],['Kaoru Mitoma','22'],['Yankuba Minteh','17'],['Lewis Dunk','6']];
 const mouth={l:.18,r:.82,t:.105,b:.425};
 const zones=[{x:.25,y:.18,n:'left'},{x:.25,y:.30,n:'left'},{x:.25,y:.40,n:'left'},{x:.5,y:.29,n:'centre'},{x:.75,y:.18,n:'right'},{x:.75,y:.30,n:'right'},{x:.75,y:.40,n:'right'}];
 let state;
 function resetGame(){state={turn:'albion',a:0,p:0,ak:[],pk:[],busy:false,round:0,aim:{x:.5,y:.29},panenka:false};resetActors();ready.hidden=true;update();setAim(.5,.29)}
 function marker(id,arr){const e=$(id);if(e)e.innerHTML=arr.map(v=>`<i class="${v?'scored':'missed'}">${v?'●':'×'}</i>`).join('')}
 function update(){const shooting=state.turn==='albion';card?.classList.toggle('pointer-ready',!state.busy);badge.textContent=shooting?'ALBION PENALTY · YOU ARE SHOOTING':'PALACE PENALTY · YOU ARE VERBRUGGEN';badge.className='turn-badge '+(shooting?'albion-turn':'palace-turn');$('albionGoalCount').textContent=state.a;$('palaceGoalCount').textContent=state.p;marker('albionPenaltyMarkers',state.ak);marker('palacePenaltyMarkers',state.pk);$('shotCount').textContent=`${Math.floor(state.round/2)+1}/5`;const nm=names[Math.min(state.ak.length,names.length-1)];$('penaltyTakerName').textContent=shooting?nm[0]:'Crystal Palace';$('penaltyShirt').textContent=shooting?nm[1]:'11';status.innerHTML=shooting?'<b>Pick your spot</b><span>Aim inside the goal frame and click or tap.</span>':'<b>Ready to save</b><span>Watch the strike, then choose Verbruggen’s dive.</span>'}
 function clamp(v,a,b){return Math.max(a,Math.min(b,v))}
 function setAim(x,y){state.aim={x:clamp(x,mouth.l+.02,mouth.r-.02),y:clamp(y,mouth.t+.02,mouth.b-.02)};if(pointer){pointer.style.left=`${state.aim.x*100}%`;pointer.style.top=`${state.aim.y*100}%`}}
 function coords(ev){const r=goal.getBoundingClientRect();return{x:(ev.clientX-r.left)/r.width,y:(ev.clientY-r.top)/r.height}}
 function resetActors(){keeper.className='keeper clean-keeper-rig';taker.className='penalty-taker clean-player-rig';ball.removeAttribute('style');shadow?.removeAttribute('style');goal.classList.remove('net-impact','saved-impact')}
 function targetZone(target){return target.x<.39?'left':target.x>.61?'right':'centre'}
 function animateBall(x,y){const r=goal.getBoundingClientRect();const start={x:.5,y:.79};ball.style.left=`${start.x*100}%`;ball.style.top=`${start.y*100}%`;ball.style.transform='translate(-50%,-50%) scale(1)';ball.offsetWidth;ball.style.transition='left .62s cubic-bezier(.16,.72,.22,1),top .62s cubic-bezier(.16,.72,.22,1),transform .62s ease';ball.style.left=`${x*100}%`;ball.style.top=`${y*100}%`;ball.style.transform='translate(-50%,-50%) scale(.48)';if(shadow){shadow.style.transition='left .62s ease,top .62s ease,transform .62s ease,opacity .62s ease';shadow.style.left=`${x*100}%`;shadow.style.top=`${Math.min(.48,y+.08)*100}%`;shadow.style.transform='translate(-50%,-50%) scale(.35)';shadow.style.opacity='.18'}}
 async function act(){if(state.busy)return;state.busy=true;card?.classList.remove('pointer-ready');const shooting=state.turn==='albion';resetActors();
  if(shooting){taker.classList.add('running');await wait(430);taker.classList.add('kicking');await wait(145);const spread=.018;const target=state.panenka?{x:.5,y:.34}:{x:clamp(state.aim.x+(Math.random()-.5)*spread,mouth.l,mouth.r),y:clamp(state.aim.y+(Math.random()-.5)*spread,mouth.t,mouth.b)};target.n=targetZone(target);const dive=zones[Math.floor(Math.random()*zones.length)].n;animateBall(target.x,target.y);await wait(115);keeper.classList.add('diving-'+dive);const accurate=Math.random()>.08,saved=accurate&&dive===target.n&&Math.random()<.62;await wait(520);const scored=accurate&&!saved;goal.classList.add(scored?'net-impact':saved?'saved-impact':'');state.ak.push(scored);if(scored)state.a++;status.innerHTML=scored?'<b>GOAL!</b><span>The ball finds the net.</span>':saved?'<b>SAVED</b><span>The keeper reaches it.</span>':'<b>MISS</b><span>Just outside the frame.</span>';state.panenka=false;
  }else{await wait(320);const target=zones[Math.floor(Math.random()*zones.length)];animateBall(target.x,target.y);await wait(120);const dive=targetZone(state.aim);keeper.classList.add('diving-'+dive);await wait(500);const saved=dive===target.n&&Math.random()<.76;goal.classList.add(saved?'saved-impact':'net-impact');state.pk.push(!saved);if(!saved)state.p++;status.innerHTML=saved?'<b>SAVED!</b><span>Verbruggen keeps it out.</span>':'<b>GOAL</b><span>Palace score.</span>'}
  state.round++;await wait(500);if(finished()){state.busy=false;ready.hidden=true;status.innerHTML=`<b>${state.a>state.p?'ALBION WIN!':state.a<state.p?'PALACE WIN':'LEVEL'}</b><span>Final score ${state.a}-${state.p}.</span>`;return}state.turn=shooting?'palace':'albion';state.busy=false;ready.hidden=false;readyText.textContent=state.turn==='albion'?'Albion’s next taker is ready.':'Take your place as Bart Verbruggen.';update()}
 function finished(){const aN=state.ak.length,pN=state.pk.length;if(aN<5||pN<5)return state.a+(5-aN)<state.p||state.p+(5-pN)<state.a;return aN===pN&&state.a!==state.p}
 goal.addEventListener('pointermove',e=>{if(!state.busy){const p=coords(e);setAim(p.x,p.y)}});goal.addEventListener('pointerdown',e=>{e.preventDefault();if(!state.busy){const p=coords(e);setAim(p.x,p.y);act()}});reset?.addEventListener('click',resetGame);panenka?.addEventListener('click',()=>{if(!state.busy&&state.turn==='albion'){state.panenka=true;status.innerHTML='<b>Panenka selected</b><span>Click inside the goal to chip centrally.</span>'}});cont?.addEventListener('click',()=>{ready.hidden=true;resetActors();setAim(.5,state.turn==='albion'?.29:.29);update()});document.addEventListener('keydown',e=>{if(!card?.matches(':hover')||state.busy)return;const d=.025;if(e.key==='ArrowLeft')setAim(state.aim.x-d,state.aim.y);if(e.key==='ArrowRight')setAim(state.aim.x+d,state.aim.y);if(e.key==='ArrowUp')setAim(state.aim.x,state.aim.y-d);if(e.key==='ArrowDown')setAim(state.aim.x,state.aim.y+d);if(e.key==='Enter')act()});resetGame()
}
window.addEventListener('DOMContentLoaded',initShootout);
})();