(()=>{'use strict';
const $=id=>document.getElementById(id), wait=ms=>new Promise(r=>setTimeout(r,ms));
function replace(id){const n=$(id);if(!n)return null;const c=n.cloneNode(true);n.replaceWith(c);return c}
function svgPortrait(name,shirt){const initials=name.split(/\s+/).map(x=>x[0]).join('').slice(0,2);return 'data:image/svg+xml;charset=utf-8,'+encodeURIComponent(`<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 300 360"><defs><linearGradient id="g" x2="1" y2="1"><stop stop-color="#0b5cab"/><stop offset="1" stop-color="#7ec8ff"/></linearGradient></defs><rect width="300" height="360" fill="url(#g)"/><circle cx="150" cy="112" r="56" fill="#c98b63"/><path d="M96 103q12-68 108-13v31q-54-30-108 0z" fill="#33231c"/><path d="M55 360v-113q0-67 95-67t95 67v113" fill="#fff"/><path d="M70 360v-128h35v128m45 0V195h35v165m45 0V230h35v130" fill="#1474d4"/><text x="150" y="285" text-anchor="middle" font-family="Arial" font-size="72" font-weight="800" fill="#17233c">${initials}</text><text x="150" y="330" text-anchor="middle" font-family="Arial" font-size="24" font-weight="700" fill="#17233c">${shirt}</text></svg>`)}
function initGuess(){
 const start=replace('guessStart'),next=replace('guessNextClue'),choices=replace('guessChoices'); if(!start||!next||!choices)return;
 const clue=$('guessClue'),result=$('guessResult'),img=$('guessPlayerImage'),sil=img?.closest('.guess-silhouette');
 const players=[
 {n:'Lewis Dunk',s:'6',c:['I made my Albion debut before the Amex opened.','I captained the club through its longest Premier League era.','I am a Brighton-born central defender.']},
 {n:'Kaoru Mitoma',s:'22',c:['My route to the first team included a Belgian loan.','I wrote a university thesis about dribbling.','I am a Japanese winger.']},
 {n:'Bart Verbruggen',s:'1',c:['I arrived after playing in Belgium.','I became a regular international while still in my early twenties.','I am Albion’s Dutch goalkeeper.']},
 {n:'João Pedro',s:'9',c:['I previously played in Hertfordshire.','Penalties supplied several of my early Albion goals.','I am a Brazilian forward.']},
 {n:'Danny Welbeck',s:'18',c:['I have scored in the Premier League for four clubs.','I represented England at two World Cups.','I am Albion’s experienced centre-forward.']},
 {n:'Pervis Estupiñán',s:'30',c:['My career has included spells in Spain and England.','I am known for powerful overlaps from the left.','I am an Ecuador international full-back.']},
 {n:'Carlos Baleba',s:'20',c:['I moved to England from Lille.','I combine ball-winning with powerful forward running.','I am a Cameroon midfielder.']},
 {n:'Yankuba Minteh',s:'17',c:['I developed in Denmark before moving to English football.','I spent a season on loan in Rotterdam.','I am a Gambian winger.']}
 ]; let current=null,idx=0,last='';
 function draw(){let pool=players.filter(p=>p.n!==last);current=pool[Math.floor(Math.random()*pool.length)];last=current.n;idx=0;clue.textContent=current.c[0];result.textContent='';next.disabled=false;next.textContent='Next clue';choices.innerHTML='';sil?.classList.remove('reveal-2','reveal-3','revealed');sil?.classList.add('has-image');img.src=svgPortrait(current.n,current.s);img.alt=`Illustrated portrait clue for ${current.n}`;
 const wrong=players.filter(p=>p.n!==current.n).sort(()=>Math.random()-.5).slice(0,3);[current,...wrong].sort(()=>Math.random()-.5).forEach(p=>{const b=document.createElement('button');b.type='button';b.textContent=p.n;b.addEventListener('click',()=>answer(p.n,b));choices.appendChild(b)});start.textContent='New player'}
 function answer(name,b){const ok=name===current.n;[...choices.children].forEach(x=>{x.disabled=true;if(x.textContent===current.n)x.classList.add('correct')});if(!ok)b.classList.add('incorrect');result.textContent=ok?`Correct — ${current.n}.`:`Not this time — it was ${current.n}.`;sil?.classList.add('revealed');next.disabled=true}
 start.addEventListener('click',draw);next.addEventListener('click',()=>{if(!current)return;idx=Math.min(2,idx+1);clue.textContent=current.c[idx];sil?.classList.toggle('reveal-2',idx===1);sil?.classList.toggle('reveal-3',idx===2);if(idx===2){next.disabled=true;next.textContent='Final clue shown'}})
}
function initShootout(){
 const goal=replace('goal'),reset=replace('resetShootout'),panenka=replace('panenkaButton'),cont=replace('continueShootout'); if(!goal)return;
 const card=$('shootout'),keeper=$('keeper'),taker=$('penaltyTaker'),ball=$('ball'),pointer=$('aimPointer'),status=$('shootoutStatus'),badge=$('turnBadge'),ready=$('turnReadyPanel'),readyText=$('turnReadyText');
 const names=[['João Pedro','9'],['Danny Welbeck','18'],['Kaoru Mitoma','22'],['Yankuba Minteh','17'],['Lewis Dunk','6']];let state;
 const zones=[{x:.18,y:.22,n:'left'},{x:.18,y:.53,n:'left'},{x:.18,y:.79,n:'left'},{x:.5,y:.5,n:'centre'},{x:.82,y:.22,n:'right'},{x:.82,y:.53,n:'right'},{x:.82,y:.79,n:'right'}];
 function resetGame(){state={turn:'albion',a:0,p:0,ak:[],pk:[],busy:false,round:0,aim:{x:.5,y:.38},panenka:false};keeper.className='keeper clean-keeper-rig';taker.className='penalty-taker clean-player-rig';ball.removeAttribute('style');ready.hidden=true;update();setAim(.5,.38)}
 function marker(id,arr){const e=$(id);if(e)e.innerHTML=arr.map(v=>`<i class="${v?'scored':'missed'}">${v?'●':'×'}</i>`).join('')}
 function update(){const shooting=state.turn==='albion';card?.classList.toggle('pointer-ready',!state.busy);badge.textContent=shooting?'ALBION PENALTY · YOU ARE SHOOTING':'PALACE PENALTY · YOU ARE VERBRUGGEN';badge.className='turn-badge '+(shooting?'albion-turn':'palace-turn');$('albionGoalCount').textContent=state.a;$('palaceGoalCount').textContent=state.p;marker('albionPenaltyMarkers',state.ak);marker('palacePenaltyMarkers',state.pk);$('shotCount').textContent=`${Math.floor(state.round/2)+1}/5`;const nm=names[Math.min(state.ak.length,names.length-1)];$('penaltyTakerName').textContent=shooting?nm[0]:'Crystal Palace';$('penaltyShirt').textContent=shooting?nm[1]:'11';status.innerHTML=shooting?'<b>Pick your spot</b><span>Move the pointer and click or tap inside the goal.</span>':'<b>Ready to save</b><span>Choose where Verbruggen should dive.</span>'}
 function setAim(x,y){state.aim={x:Math.max(.08,Math.min(.92,x)),y:Math.max(.12,Math.min(.86,y))};if(pointer){pointer.style.left=`${state.aim.x*100}%`;pointer.style.top=`${state.aim.y*100}%`}}
 function coords(ev){const r=goal.getBoundingClientRect();return {x:(ev.clientX-r.left)/r.width,y:(ev.clientY-r.top)/r.height}}
 function resetActors(){keeper.className='keeper clean-keeper-rig';taker.className='penalty-taker clean-player-rig';ball.removeAttribute('style')}
 async function act(){if(state.busy)return;state.busy=true;card?.classList.remove('pointer-ready');const shooting=state.turn==='albion';resetActors();if(shooting){taker.classList.add('running');await wait(420);taker.classList.add('kicking');await wait(130);const target=state.panenka?{x:.5,y:.43,n:'centre'}:{...state.aim,n:state.aim.x<.38?'left':state.aim.x>.62?'right':'centre'};const dive=zones[Math.floor(Math.random()*zones.length)].n;keeper.classList.add('diving-'+dive);const accurate=Math.random()>.11, saved=accurate&&dive===target.n&&Math.random()<.68;animateBall(target.x,target.y);await wait(650);const goalScored=accurate&&!saved;state.ak.push(goalScored);if(goalScored)state.a++;status.innerHTML=goalScored?'<b>GOAL!</b><span>Albion convert.</span>':saved?'<b>SAVED</b><span>The keeper gets there.</span>':'<b>MISS</b><span>Just wide.</span>';state.panenka=false}else{await wait(280);const target=zones[Math.floor(Math.random()*zones.length)];animateBall(target.x,target.y);await wait(90);const dive=state.aim.x<.38?'left':state.aim.x>.62?'right':'centre';keeper.classList.add('diving-'+dive);await wait(560);const saved=dive===target.n&&Math.random()<.78;state.pk.push(!saved);if(!saved)state.p++;status.innerHTML=saved?'<b>SAVED!</b><span>Verbruggen keeps it out.</span>':'<b>GOAL</b><span>Palace score.</span>'}
 state.round++;await wait(500);if(finished()){state.busy=false;card?.classList.remove('pointer-ready');ready.hidden=true;status.innerHTML=`<b>${state.a>state.p?'ALBION WIN!':state.a<state.p?'PALACE WIN':'LEVEL'}</b><span>Final score ${state.a}-${state.p}.</span>`;return}state.turn=shooting?'palace':'albion';state.busy=false;ready.hidden=false;readyText.textContent=state.turn==='albion'?'Albion’s next taker is ready.':'Take your place as Bart Verbruggen.';update()}
 function finished(){const aN=state.ak.length,pN=state.pk.length;if(aN<5||pN<5){return state.a+(5-aN)<state.p||state.p+(5-pN)<state.a}return aN===pN&&state.a!==state.p}
 function animateBall(x,y){const r=goal.getBoundingClientRect();ball.style.transition='transform .58s cubic-bezier(.2,.8,.25,1)';ball.style.transform=`translate(${(x-.5)*r.width*.82}px,${(y-.82)*r.height*.72}px) scale(.55)`}
 goal.addEventListener('pointermove',e=>{if(!state.busy){const p=coords(e);setAim(p.x,p.y)}});goal.addEventListener('pointerdown',e=>{e.preventDefault();if(!state.busy){const p=coords(e);setAim(p.x,p.y);act()}});reset?.addEventListener('click',resetGame);panenka?.addEventListener('click',()=>{if(!state.busy&&state.turn==='albion'){state.panenka=true;status.innerHTML='<b>Panenka selected</b><span>Click the goal to chip centrally.</span>'}});cont?.addEventListener('click',()=>{ready.hidden=true;resetActors();setAim(.5,state.turn==='albion'?.38:.5);update()});document.addEventListener('keydown',e=>{if(!card?.matches(':hover')||state.busy)return;const d=.04;if(e.key==='ArrowLeft')setAim(state.aim.x-d,state.aim.y);if(e.key==='ArrowRight')setAim(state.aim.x+d,state.aim.y);if(e.key==='ArrowUp')setAim(state.aim.x,state.aim.y-d);if(e.key==='ArrowDown')setAim(state.aim.x,state.aim.y+d);if(e.key==='Enter')act()});resetGame()
}
window.addEventListener('DOMContentLoaded',()=>{initGuess();initShootout()});
})();
