(()=>{
'use strict';
const $=id=>document.getElementById(id);
const stage=$('penaltyStage'); if(!stage)return;
const goal=$('goalMouth'),keeper=$('keeperFigure'),taker=$('takerFigure'),ball=$('penaltyBall'),shadow=$('penaltyBallShadow'),reticle=$('aimReticle');
const readyPanel=$('palaceReadyPanel'),readyButton=$('palaceReadyButton'),status=$('shootoutStatus'),turnBadge=$('turnBadge'),nameEl=$('penaltyTakerName'),approach=$('penaltyApproach'),situation=$('shootoutSituation');
const albionCount=$('albionGoalCount'),palaceCount=$('palaceGoalCount'),roundEl=$('shotCount'),mini=$('stadiumMiniScore'),decision=$('kickDecision'),reaction=$('reactionCue');
const resetBtn=$('resetShootout'),shareBtn=$('shareShootout'),summary=$('shootoutSummary'),fullscreen=$('fullscreenShootout');
const albionMarkers=$('albionPenaltyMarkers'),palaceMarkers=$('palacePenaltyMarkers'),shirt=$('penaltyShirt'),instruction=$('stageInstruction');
if(readyPanel.parentElement!==stage)stage.appendChild(readyPanel);
const players=[['Danny Welbeck','18','Right foot · measured run-up'],['João Pedro','9','Right foot · composed approach'],['Kaoru Mitoma','22','Right foot · angled run-up'],['Brajan Gruda','8','Left foot · short run-up'],['Lewis Dunk','5','Right foot · powerful strike']];
let state={turn:'albion',round:0,a:0,p:0,aShots:[],pShots:[],phase:'aim',aim:{x:.5,y:.5},token:0,save:null,finished:false};
const sleep=ms=>new Promise(r=>setTimeout(r,ms)); const clamp=(v,a,b)=>Math.max(a,Math.min(b,v));
function setStatus(title,text){status.innerHTML=`<b>${title}</b><span>${text}</span>`}
function markers(el,arr){el.innerHTML='';for(let i=0;i<5;i++){const m=document.createElement('i');if(arr[i]===true)m.className='goal';if(arr[i]===false)m.className='miss';el.appendChild(m)}}
function updateScore(){albionCount.textContent=state.a;palaceCount.textContent=state.p;roundEl.textContent=`${Math.min(5,state.round+1)}/5`;mini.textContent=`${state.a}–${state.p}`;markers(albionMarkers,state.aShots);markers(palaceMarkers,state.pShots)}
function clearClasses(){['placing','runup','strike','gk-bottle','gk-bar','gk-point-left','gk-point-right','gk-dive-left','gk-dive-right','gk-centre','is-aiming','is-save-window'].forEach(c=>stage.classList.remove(c));goal.classList.remove('net-hit','bar-hit');keeper.style.transform='';taker.style.transform='';ball.style.transition='none';ball.style.transform='translate(-50%,-50%)';}
function resetObjects(){clearClasses();ball.style.left='50%';ball.style.top='76%';shadow.style.left='50%';shadow.style.top='77.5%';shadow.style.opacity='1';reticle.style.left='50%';reticle.style.top='31%';state.aim={x:.5,y:.5};decision.hidden=true;reaction.hidden=true;}
function showDecision(text){decision.textContent=text;decision.hidden=false;setTimeout(()=>decision.hidden=true,1000)}
function finishCheck(){const remainingA=5-state.aShots.length,remainingP=5-state.pShots.length;if(state.a>state.p+remainingP||state.p>state.a+remainingA||(state.aShots.length>=5&&state.pShots.length>=5&&state.a!==state.p)){state.finished=true;const win=state.a>state.p;summary.hidden=false;summary.innerHTML=`<strong>${win?'ALBION WIN':'PALACE WIN'} ${state.a}–${state.p}</strong><p>${win?'The Seagulls win the shoot-out.':'Palace take the shoot-out.'}</p>`;shareBtn.hidden=false;setStatus('Shoot-out complete','Restart to play again.');instruction.textContent='Shoot-out complete';return true}return false}
function setupAlbion(){state.turn='albion';state.phase='aim';resetObjects();const p=players[state.round%players.length];nameEl.textContent=p[0];shirt.textContent=p[1];approach.textContent=p[2];turnBadge.textContent='ALBION PENALTY';turnBadge.className='turn-badge albion-turn';situation.textContent='Pick your spot';stage.classList.add('is-aiming');readyPanel.hidden=true;instruction.textContent='Drag or tap inside the goal to aim';setStatus('Pick your spot','The target resets to the centre for every Brighton penalty.');}
async function placement(token){stage.classList.add('placing');setStatus('Placing the ball','The taker walks in, settles the ball and steps back.');await sleep(3500);if(token!==state.token)return;stage.classList.remove('placing');await sleep(450)}
async function runAndStrike(token,target,who){stage.classList.add('runup');setStatus('Run-up','The taker approaches the ball.');await sleep(900);if(token!==state.token)return;stage.classList.remove('runup');stage.classList.add('strike');await sleep(180);if(token!==state.token)return;stage.classList.remove('strike');await flyBall(target,who)}
function targetPx(t){const r=goal.getBoundingClientRect(),s=stage.getBoundingClientRect();return{x:(r.left-s.left+r.width*t.x)/s.width,y:(r.top-s.top+r.height*t.y)/s.height}}
async function flyBall(target,who){const end=targetPx(target);ball.style.transition='left .62s cubic-bezier(.2,.75,.25,1),top .62s cubic-bezier(.2,.75,.25,1),transform .62s linear';shadow.style.transition='left .62s,top .62s,opacity .62s';ball.style.left=`${end.x*100}%`;ball.style.top=`${end.y*100}%`;ball.style.transform='translate(-50%,-50%) scale(.55) rotate(540deg)';shadow.style.left=`${end.x*100}%`;shadow.style.top=`${Math.min(.92,end.y+.03)*100}%`;shadow.style.opacity='.12';await sleep(650);goal.classList.add('net-hit');await sleep(420)}
async function takeAlbion(){if(state.phase!=='aim'||state.finished)return;state.phase='busy';stage.classList.remove('is-aiming');const token=++state.token;const target={...state.aim};await placement(token);await runAndStrike(token,target,'albion');if(token!==state.token)return;const difficulty=Math.abs(target.x-.5)+Math.abs(target.y-.5);const scored=Math.random() < clamp(.73+difficulty*.18,.72,.9);if(scored){state.a++;goal.classList.add('net-hit');showDecision('GOAL!')}else{const side=target.x<.43?'left':target.x>.57?'right':'centre';stage.classList.add(side==='centre'?'gk-centre':`gk-dive-${side}`);showDecision('SAVED!')}state.aShots.push(scored);updateScore();await sleep(1300);if(finishCheck())return;setupPalaceReady()}
function setupPalaceReady(){state.turn='palace';state.phase='ready';resetObjects();nameEl.textContent='Crystal Palace taker';approach.textContent='Watch the run-up and react';turnBadge.textContent='PALACE PENALTY';turnBadge.className='turn-badge palace-turn';situation.textContent='You are Verbruggen';readyPanel.hidden=false;instruction.textContent='Press READY TO SAVE';setStatus('Get ready','The button is on the pitch and disappears when pressed.');}
async function goalkeeperRoutine(token){stage.classList.add('gk-bottle');setStatus('Bottle check','Verbruggen walks to the bottle, reads it and returns.');await sleep(3200);if(token!==state.token)return;stage.classList.remove('gk-bottle');await sleep(250);stage.classList.add('gk-bar');setStatus('Crossbar routine','He jumps, touches the bar and lands on the line.');await sleep(520);goal.classList.add('bar-hit');await sleep(450);if(token!==state.token)return;stage.classList.remove('gk-bar');goal.classList.remove('bar-hit');const side=Math.random()<.5?'left':'right';stage.classList.add(`gk-point-${side}`);setStatus('Mind games','Verbruggen points towards one corner.');await sleep(850);stage.classList.remove(`gk-point-${side}`);await sleep(300)}
async function startPalace(){if(state.phase!=='ready'||state.finished)return;readyPanel.hidden=true;state.phase='busy';const token=++state.token;await placement(token);await goalkeeperRoutine(token);if(token!==state.token)return;reaction.hidden=false;stage.classList.add('is-save-window');instruction.textContent='Swipe left or right, tap, or stay central';setStatus('Palace run-up','React now. Staying central can save a straight penalty.');await sleep(650);reaction.hidden=true;await runAndStrike(token,{x:.25+Math.random()*.5,y:.22+Math.random()*.55},'palace');if(token!==state.token)return;stage.classList.remove('is-save-window');const shot=Math.random()<.33?'left':Math.random()<.5?'right':'centre';const save=state.save||'centre';const saved=save===shot && Math.random()<.68;if(saved){stage.classList.add(shot==='centre'?'gk-centre':`gk-dive-${shot}`);showDecision('SAVED!')}else{state.p++;goal.classList.add('net-hit');showDecision('GOAL')}state.pShots.push(!saved);updateScore();state.round++;await sleep(1300);if(finishCheck())return;setupAlbion()}
function aimFromEvent(e){if(state.phase!=='aim')return;const r=goal.getBoundingClientRect();const x=clamp((e.clientX-r.left)/r.width,.08,.92),y=clamp((e.clientY-r.top)/r.height,.12,.88);state.aim={x,y};const s=stage.getBoundingClientRect();reticle.style.left=`${((r.left-s.left+r.width*x)/s.width)*100}%`;reticle.style.top=`${((r.top-s.top+r.height*y)/s.height)*100}%`;}
stage.addEventListener('pointerdown',e=>{if(state.phase==='aim'){stage.setPointerCapture?.(e.pointerId);aimFromEvent(e)}else if(state.phase==='busy'&&stage.classList.contains('is-save-window')){state.save=e.clientX<stage.getBoundingClientRect().left+stage.clientWidth*.4?'left':e.clientX>stage.getBoundingClientRect().left+stage.clientWidth*.6?'right':'centre';showDecision(state.save.toUpperCase())}});
stage.addEventListener('pointermove',e=>{if(state.phase==='aim'&&e.buttons)aimFromEvent(e)});stage.addEventListener('pointerup',e=>{if(state.phase==='aim'){aimFromEvent(e);takeAlbion()}});
stage.addEventListener('keydown',e=>{if(state.phase==='aim'){if(e.key==='ArrowLeft')state.aim.x=clamp(state.aim.x-.05,.08,.92);if(e.key==='ArrowRight')state.aim.x=clamp(state.aim.x+.05,.08,.92);if(e.key==='ArrowUp')state.aim.y=clamp(state.aim.y-.05,.12,.88);if(e.key==='ArrowDown')state.aim.y=clamp(state.aim.y+.05,.12,.88);if(e.key==='Enter')takeAlbion()}else if(stage.classList.contains('is-save-window')){if(e.key==='ArrowLeft')state.save='left';if(e.key==='ArrowRight')state.save='right';if(e.key==='ArrowDown'||e.key==='Enter')state.save='centre'}});
readyButton.addEventListener('click',startPalace);resetBtn.addEventListener('click',reset);fullscreen?.addEventListener('click',()=>{const card=$('shootout');if(document.fullscreenElement)document.exitFullscreen();else card.requestFullscreen?.()});shareBtn?.addEventListener('click',()=>navigator.share?.({title:'Albion shoot-out',text:`Albion ${state.a}-${state.p} Palace`}).catch(()=>{}));
function reset(){state={turn:'albion',round:0,a:0,p:0,aShots:[],pShots:[],phase:'aim',aim:{x:.5,y:.5},token:state.token+1,save:null,finished:false};summary.hidden=true;shareBtn.hidden=true;updateScore();setupAlbion()}
reset();
})();
